### ISSUE TITLE
Error when saving dot file

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-noetic-arch/ros-noetic-rqt-graph#1]
Identical with https://github.com/ros-visualization/rqt_graph/issues/67

**Comment by AchmadFathoni** [comment]
> Identical with [ros-visualization/rqt_graph#67](https://github.com/ros-visualization/rqt_graph/issues/67)

When it is resolved the next error is identical with https://github.com/ros-visualization/rqt_common_plugins/issues/393

**Comment by AchmadFathoni** [comment]
> > Identical with [ros-visualization/rqt_graph#67](https://github.com/ros-visualization/rqt_graph/issues/67)
> 
> When it is resolved the next error is identical with [ros-visualization/rqt_common_plugins#393](https://github.com/ros-visualization/rqt_common_plugins/issues/393)

Wait I think it little bit different, my error is
```
Expected {'GRAPH' | 'DIGRAPH'}  (at char 0), (line:1, col:1)
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3.10/site-packages/rqt_graph/ros_graph.py", line 399, in _load_dot
    self._update_graph_view(dotcode.decode('utf-8'))
  File "/opt/ros/noetic/lib/python3.10/site-packages/rqt_graph/ros_graph.py", line 330, in _update_graph_view
    self._redraw_graph_view()
  File "/opt/ros/noetic/lib/python3.10/site-packages/rqt_graph/ros_graph.py", line 361, in _redraw_graph_view
    (nodes, edges) = self.dot_to_qt.dotcode_to_qt_items(self._current_dotcode,
  File "/opt/ros/noetic/lib/python3.10/site-packages/qt_dotgraph/dot_to_qt.py", line 262, in dotcode_to_qt_items
    nodes = self.parse_nodes(graph, highlight_level, scene=scene)
  File "/opt/ros/noetic/lib/python3.10/site-packages/qt_dotgraph/dot_to_qt.py", line 271, in parse_nodes
    graph.nodes_iter = graph.get_node_list
AttributeError: 'NoneType' object has no attribute 'get_node_list'

```
